name: 'Rising Cloud Deployment'
description: 'Deploy your project in Rising Cloud with GitHub Actions'
branding:
  icon: 'cloud-lightning'
  color: 'purple'
inputs:
  rising-cloud-user:
    description: 'Rising Cloud User'
    required: true
  rising-cloud-pasword:
    description: 'Rising Cloud Password'
    required: true
  working-directory:
    description: 'Optional project path'
    required: false
    default: '.'
  config-file:
    description: 'Rising Cloud YAML file'
    required: false
    default: "risingcloud.yml"
runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "Support Linux machines Only"
        exit 1
    - name: Check Password or User Info Empty
      if: ${{ inputs.rising-cloud-user == '' || inputs.rising-cloud-pasword == '' }}
      shell: bash
      run: |
        echo "User and Password cannot be empty"
        exit 1
    - name: Install ca-certificates
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y ca-certificates
        sudo touch /etc/apt/sources.list.d/fury.list
        echo "deb [trusted=yes] https://apt.fury.io/risingcloud/ /" | sudo tee -a /etc/apt/sources.list.d/fury.list
        sudo apt update && sudo apt install -y risingcloud
    - name: Login Rising Cloud
      shell: bash
      run: risingcloud login -e ${{ inputs.rising-cloud-user }} -p ${{ inputs.rising-cloud-pasword }}
    - name: Deploy Web Serive
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        risingcloud build -r -c ${{ inputs.config-file }} —d
